MATRICULA_6_DIGITOS: list[int] = [0, 2, 9, 0, 8, 8]  

UART_PORT = "/dev/ttyS0"  
UART_BAUD = 115200
UART_TIMEOUT = 2.0            

CMD_GET_INT = 0xA1
CMD_GET_FLOAT = 0xA2
CMD_GET_STRING = 0xA3
CMD_SEND_INT = 0xB1
CMD_SEND_FLOAT = 0xB2
CMD_SEND_STR = 0xB3

VALID_COMMANDS = {CMD_GET_INT, CMD_GET_FLOAT, CMD_GET_STRING,
                  CMD_SEND_INT, CMD_SEND_FLOAT, CMD_SEND_STR}
